"""
DineIQ Analytics - Menu Item Feature Engineering (SRS Step 7)
Computes the exact menu-level features specified in SRS:
 1. item_revenue: Total sales revenue generated by the item
 2. cost: Total cost incurred for the item sold
 3. contribution_margin: item_revenue - cost
 4. profit_percentage: (contribution_margin / item_revenue) * 100
 5. order_frequency: Total distinct orders containing the item
 6. item_popularity: Total units sold across all orders
 7. repeat_purchase_rate: Ratio of customers who purchased the item > 1 time
 8. average_rating: Mean customer satisfaction score (1.0 to 5.0)
 9. rating_trend: Trajectory of recent reviews vs prior baseline
10. wastage_percentage: Total wasted units / (units sold + units wasted) * 100
11. price_change_percentage: % shift between historical launch price and current base price
"""
import os
import sys
import pandas as pd
import numpy as np

CURRENT_DIR = os.path.dirname(os.path.abspath(__file__))
PROJECT_ROOT = os.path.abspath(os.path.join(CURRENT_DIR, "..", ".."))
CLEANED_DIR = os.path.join(PROJECT_ROOT, "processed_data", "cleaned")
INGESTION_DIR = os.path.join(PROJECT_ROOT, "spark_jobs", "ingestion")

if INGESTION_DIR not in sys.path:
    sys.path.append(INGESTION_DIR)
from spark_compat import get_spark_session


def compute_menu_features(spark=None) -> pd.DataFrame:
    """
    Computes all 11 Menu Item features using Spark SQL / PySpark DataFrames.
    Returns a pandas DataFrame with one row per menu item.
    """
    if spark is None:
        spark = get_spark_session("DineIQ-MenuFeatures")

    print("[MenuFeatures] Loading cleaned datasets into Spark...")
    
    def load_clean(name):
        pq = os.path.join(CLEANED_DIR, name, f"{name}.parquet")
        if os.path.exists(pq):
            return spark.read.parquet(pq)
        csv = os.path.join(CLEANED_DIR, name, f"{name}.csv")
        return spark.read.option("header", "true").option("inferSchema", "true").csv(csv)

    df_menu = load_clean("menu_items")
    df_items = load_clean("order_items")
    df_orders = load_clean("orders")
    df_ratings = load_clean("ratings")
    df_wastage = load_clean("wastage")
    df_pricing = load_clean("pricing_history")
    df_cats = load_clean("menu_categories")

    df_menu.createOrReplaceTempView("menu_items")
    df_items.createOrReplaceTempView("order_items")
    df_orders.createOrReplaceTempView("orders")
    df_ratings.createOrReplaceTempView("ratings")
    df_wastage.createOrReplaceTempView("wastage")
    df_pricing.createOrReplaceTempView("pricing_history")
    df_cats.createOrReplaceTempView("menu_categories")

    print("[MenuFeatures] Computing sales volume, revenue, cost, and contribution margin...")
    sales_df = spark.sql("""
        SELECT 
            oi.item_id,
            ROUND(SUM(oi.item_total), 2) AS item_revenue,
            ROUND(SUM(oi.quantity * m.cost_price), 2) AS cost,
            ROUND(SUM(oi.item_total) - SUM(oi.quantity * m.cost_price), 2) AS contribution_margin,
            ROUND(((SUM(oi.item_total) - SUM(oi.quantity * m.cost_price)) / NULLIF(SUM(oi.item_total), 0)) * 100, 2) AS profit_percentage,
            COUNT(DISTINCT oi.order_id) AS order_frequency,
            SUM(oi.quantity) AS item_popularity
        FROM order_items oi
        JOIN menu_items m ON oi.item_id = m.item_id
        GROUP BY oi.item_id
    """)
    sales_df.createOrReplaceTempView("sales_metrics")

    print("[MenuFeatures] Computing repeat-purchase rate per menu item...")
    repeat_df = spark.sql("""
        WITH cust_item_counts AS (
            SELECT 
                oi.item_id,
                o.customer_id,
                COUNT(DISTINCT oi.order_id) AS orders_count
            FROM order_items oi
            JOIN orders o ON oi.order_id = o.order_id
            WHERE o.customer_id != 'CUST-GUEST'
            GROUP BY oi.item_id, o.customer_id
        )
        SELECT 
            item_id,
            ROUND(
                COUNT(DISTINCT CASE WHEN orders_count > 1 THEN customer_id END) / 
                NULLIF(COUNT(DISTINCT customer_id), 0), 
                4
            ) AS repeat_purchase_rate
        FROM cust_item_counts
        GROUP BY item_id
    """)
    repeat_df.createOrReplaceTempView("repeat_metrics")

    print("[MenuFeatures] Computing average rating and rating trend...")
    ratings_df = spark.sql("""
        WITH ranked_reviews AS (
            SELECT 
                item_id,
                overall_rating,
                review_date,
                ROW_NUMBER() OVER (PARTITION BY item_id ORDER BY review_date DESC) as recency_rank,
                COUNT(*) OVER (PARTITION BY item_id) as total_reviews
            FROM ratings
        )
        SELECT 
            item_id,
            ROUND(AVG(overall_rating), 2) AS average_rating,
            ROUND(
                AVG(CASE WHEN recency_rank <= (total_reviews * 0.3) THEN overall_rating END) -
                AVG(CASE WHEN recency_rank > (total_reviews * 0.7) THEN overall_rating END),
                3
            ) AS rating_trend
        FROM ranked_reviews
        GROUP BY item_id
    """)
    ratings_df.createOrReplaceTempView("rating_metrics")

    print("[MenuFeatures] Computing wastage percentage...")
    waste_df = spark.sql("""
        SELECT 
            item_id,
            ROUND(SUM(quantity_wasted), 2) AS total_wasted_units
        FROM wastage
        GROUP BY item_id
    """)
    waste_df.createOrReplaceTempView("waste_metrics")

    print("[MenuFeatures] Computing historical price change percentage...")
    price_df = spark.sql("""
        WITH earliest_price AS (
            SELECT 
                item_id,
                base_price AS original_price,
                ROW_NUMBER() OVER (PARTITION BY item_id ORDER BY effective_start_date ASC) as seq
            FROM pricing_history
        )
        SELECT item_id, original_price
        FROM earliest_price
        WHERE seq = 1
    """)
    price_df.createOrReplaceTempView("price_metrics")

    print("[MenuFeatures] Assembling unified Menu Feature Mart...")
    final_spark_df = spark.sql("""
        SELECT 
            m.item_id,
            m.name AS item_name,
            m.category_id,
            c.category_name,
            m.base_price,
            m.cost_price,
            COALESCE(s.item_revenue, 0.0) AS item_revenue,
            COALESCE(s.cost, 0.0) AS cost,
            COALESCE(s.contribution_margin, 0.0) AS contribution_margin,
            COALESCE(s.profit_percentage, 0.0) AS profit_percentage,
            COALESCE(s.order_frequency, 0) AS order_frequency,
            COALESCE(s.item_popularity, 0) AS item_popularity,
            COALESCE(r.repeat_purchase_rate, 0.0) AS repeat_purchase_rate,
            COALESCE(rt.average_rating, 0.0) AS average_rating,
            COALESCE(rt.rating_trend, 0.0) AS rating_trend,
            ROUND(
                COALESCE(w.total_wasted_units, 0.0) / 
                NULLIF(COALESCE(s.item_popularity, 0) + COALESCE(w.total_wasted_units, 0.0), 0) * 100, 
                2
            ) AS wastage_percentage,
            ROUND(
                ((m.base_price - COALESCE(p.original_price, m.base_price)) / 
                NULLIF(COALESCE(p.original_price, m.base_price), 0)) * 100, 
                2
            ) AS price_change_percentage
        FROM menu_items m
        JOIN menu_categories c ON m.category_id = c.category_id
        LEFT JOIN sales_metrics s ON m.item_id = s.item_id
        LEFT JOIN repeat_metrics r ON m.item_id = r.item_id
        LEFT JOIN rating_metrics rt ON m.item_id = rt.item_id
        LEFT JOIN waste_metrics w ON m.item_id = w.item_id
        LEFT JOIN price_metrics p ON m.item_id = p.item_id
        ORDER BY s.item_revenue DESC
    """)

    pdf = final_spark_df.toPandas()
    pdf["wastage_percentage"] = pdf["wastage_percentage"].fillna(0.0)
    pdf["price_change_percentage"] = pdf["price_change_percentage"].fillna(0.0)
    print(f"[MenuFeatures] Successfully calculated 11 menu features for {len(pdf)} items!")
    return pdf

if __name__ == "__main__":
    df = compute_menu_features()
    print(df.head(10).to_string())
